---
title: "Mapping a City's Road Network"
categories: [Analysis, Python, OSM, Basic]
---

# Overview

The goal of this project is to extract, clean, and visualize the road network of Hod Hasharon using [OpenStreetMap](https://wiki.openstreetmap.org/wiki/Main_Page) data, while demonstrating a basic spatial workflow and basic Python tools like OSMnx, geopandas and matplotlib.

[Hod Hasharon](https://en.wikipedia.org/wiki/Hod_HaSharon) is a typical suburban city, with population of over 65,000. Most of the population works outside the city, which creates heavy traffic on the outer axis routes, especially during morning hours.

## Spatial tools used in this project
[GeoPandas](https://geopandas.org/en/stable/) for a spatial analysis.

[OSMnx](https://osmnx.readthedocs.io/en/stable/index.html) is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.

## Work stages

This basic workflow include:

- Download spatial data from OpenStreetMap using OSMnx
- Basic GeoDataFrame inspection and cleaning
- CRS transformation and why it matters
- Simple spatial analysis (length by road type)
- Basic static and interactive visualization 


# Getting the data

We'll start by importing the necessary packages:
```{python}
import osmnx as ox
import pandas as pd
import geopandas as gpd
```

## Define the place / boundaries
First, we'll get the city boundaries using the `ox.geocode_to_gdf()` function. This has 2 main roles:

 - Make sure that OSM recognizes the place's name.

 - Create a polygon of the place's border which we can use later

```{python}
city_name = "Hod Hasharon, Israel"

boundary = ox.geocode_to_gdf(city_name)
boundary.head()
```

**`boundary` object type:** *`{python} type(boundary)`*

**`boundary` CRS:**

```{python}
# Confirm CRS:
boundary.crs
```

**`boundary` Basic plot:**

```{python}
# Basic plot
boundary.plot()
```

## Load the roads dataset

::: {.callout-note}
In this section we'll load the full dataset and clean the data after loading, using `geopandas`
:::

Now we can load the roads and paths. First we need to define the *tags*.\
`tags` is the key:value of the map feature we want to load. full list of the tags can be found [here](https://wiki.openstreetmap.org/wiki/Map_features).\
We'll use `'road_type': True` to retrieve the whole roads, paths and cycle tracks and other recognised routes.

`OSMnx` has a few `features_from_*()` methods to load data, in which we'll focus on 2 of them.

### features_from_place()

This method uses the place name we confirmed earlier, it's simpler method but depends on OSM's place definitions:

```{python}
# Defining 'tags' (the value can be a list of specific features)
tags = {'highway': True}

# Using features_from_place()
city_roads = ox.features_from_place(city_name, tags=tags)
```
We got `{python} city_roads.shape[0]` features with `{python} city_roads.shape[1]` attributes

### features_from_polygon()

In this method we use the polygon object we created, which gives more control and especially useful with custom boundaries:

```{python}
# Using features_from_polygon()
city_roads_from_polygon = ox.features_from_polygon(boundary.geometry.iloc[0],
                                           tags=tags)
```

:::{.callout-note}
The polygon argument is `boundary.geometry.iloc[0]` which is *`{python} type(boundary.geometry.iloc[0])`* type object
:::

Here we also got `{python} city_roads_from_polygon.shape[0]` features with `{python} city_roads_from_polygon.shape[1]` attributes

# Cleaning and filtering

```{python}
city_roads.head()
```

The 2 main things we can see from the start:

1. Not all the features are LineStrings, some of them are points (like bus stops traffic signals and so on)

2. There are 85 attributes which most are NaN

## Filtering geometry types

Let's check the geometry type we got, and filter out all non-LineString features
```{python}
city_roads.geometry.geom_type.value_counts()
```

```{python}
city_roads_linestrings = city_roads[
    city_roads.geometry.geom_type.isin(["LineString", "MultiLineString"])]
```

::: {.callout-tip}
Although there aren't any MultiLineString geometric types features in this gdf, it's a good practice to include them.
:::
After filtering, the gdf contains `{python} city_roads_linestrings.shape[0]` features

## Cleaning columns 

The necessary columns are:

- **'geometry'** - IMPORTANT!

- **'highway'** - The road type according to the OSM's key:value definition (will be changed to `road_type`)

- **'name'** - Streets name (if available)

```{python}
city_roads_linestrings = city_roads_linestrings[['geometry', 'highway', 'name']]
city_roads_linestrings.rename({"highway": "road_type"}, axis="columns", inplace=True) # Rename column
```

The clean gdf contains `{python} city_roads_linestrings.shape[0]` features and `{python} city_roads_linestrings.shape[1]` attributes

# Analysis

Now it's time for a simple analysis. Let's find out the `'road_type'`, their total length and their percentage from the total roads' length.

## Reproject the CRS

Before we add the length of the segments, we have to check the gdf's CRS to see if it has meaningful units of measurement:

```{python}
# Check gdf CRS 
city_roads_linestrings.crs
```

```{python}
city_roads_linestrings.geometry.length.head()
```

In WGS84 (EPSG: 4326) coordinates and measurements are in degrees, which make distance values hard to understand and not very practical on small areas. To make measurements meaningful we need to reproject the spatial dataset to a projected CRS (ex. UTM) where units are in meters.

::: {.callout-tip}
For a full list of all the available CRSs, check [epsg.io site](https://epsg.io/)
:::

```{python}
city_roads_UTM = city_roads_linestrings.to_crs(epsg=32636)
```
So now, if we check the CRS we'll get:

```{python}
city_roads_UTM.crs
```

And if we check the length of the first few features, we'll get:
```{python}
city_roads_UTM.geometry.length.head()
```

## Adding 'length (m)' attribute

```{python}
city_roads_UTM['length (m)'] = round(city_roads_UTM.geometry.length, 2)
city_roads_UTM.head()
```
## Calculating the total length of each 'road_type' value

```{python}
roads_types = pd.DataFrame(city_roads_UTM.groupby('road_type')['length (m)'].sum())
roads_types['percent of total length'] = round((roads_types['length (m)'] / sum(roads_types['length (m)']) * 100), 2)
roads_types.sort_values(by='length (m)', ascending=False)
```


# Plotting

Before we plot the streets, we'll define an ordered categorical type of the highway values according to [OSM](https://wiki.openstreetmap.org/wiki/Map_features#Highway) and apply it to the `'road_type'` column in the gdf

```{python}
# Create ordered list of highway values in the gdf
from pandas.api.types import CategoricalDtype

highway_types_ordered = CategoricalDtype(categories=["primary", "secondary", "tertiary", "residential", "motorway_link", "primary_link", "secondary_link", "living_street", "service", "pedestrian", "track", "footway", "steps", "path", "cycleway"])

# Attaching the order to the gdf
city_roads_UTM['road_type'] = city_roads_UTM['road_type'].astype(highway_types_ordered)
```
Now we can create a simple plot of Hod Hasharon's streets with the categorical symbology:

```{python}
#| fig-cap: "Dominance of residential streets (orange shades) and pedestrian pathways (purple-blue shades)"

import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10, 8))
city_roads_UTM.plot(ax=ax,
                    column='road_type', 
                    cmap="plasma_r", 
                    legend=True,
                    categorical=True,
                    legend_kwds={"loc": "lower right",
                                 "ncol": 2,
                                 "title": "OSM Road Types",
                                 "fontsize": 9})
ax.set_axis_off()
plt.title("Hod Hasharon - Street Types (OpenStreetMap)", size=20)

plt.show()
```

```{python}
#| fig-cap: "Interactive map"
city_roads_UTM.explore(column='road_type',
                       cmap="plasma_r",
                       tiles='CartoDB positron'
                       )
```

# Conclusion

```{python}
#| echo: false

# Road types calculation for the text below
residential =  round(roads_types.loc['residential', 'percent of total length'])
connectivity = round(roads_types.loc['primary', 'percent of total length']) + round(roads_types.loc['secondary', 'percent of total length'])
pathways = round(roads_types.loc['path', 'percent of total length']) + round(roads_types.loc['footway', 'percent of total length']) + round(roads_types.loc['cycleway', 'percent of total length'])
```

As expected, in a suburban city like Hod Hasharon, most of the streets are residential type (~`{python} residential`%), in contrast to the small amount of primary and secondary types of roads (~`{python} connectivity`%) which play a key role in outer connectivity. This may be a contributing factor to morning traffic congestion.\
The relatively high share of paths, footways and cycleways (~`{python} pathways`%) also suggests a mixed-use urban environment with accessible pedestrian and cycling routes. 

# Summary

In this project we used a basic workflow to:

- Extract roads data from OpenStreetMap
- Clean and filter geometries
- Reproject data for accurate measurements
- Calculate road lengths by type
- Visualize the results

This workflow can serve as a foundation for more advanced spatial analysis projects.

## Advanced action-items

Here's some advanced action-items which can be made on this project:

- Divide the road types into 3 bins - connectivity roads, local roads, walking pathways and bicycle routes
- Compare with other cities 
- Improve visualization

