---
title: Cities' Public Parks Comparison
categories: [Analysis, Python, OSM]
---

# Overview

In this project, I compare the availability, size and accessibility of public parks across three similar cities in central Israel, located near each other. This type of analysis can support urban planning and quality-of-life assessments.

The cities are:

- [Hod Hasharon](https://en.wikipedia.org/wiki/Hod_HaSharon) (pop. \~63,000)
- [Kfar Sava](https://en.wikipedia.org/wiki/Kfar_Saba) (pop. \~101,000)
- [Raanana](https://en.wikipedia.org/wiki/Ra%27anana) (pop. \~75,000)

The cities are considered as "dormitory cities", located in the southern Sharon region in Israel and have a high socio-economic level. All three cities have central parks as well as smaller parks spread throughout residential areas.

The comparison includes the number of parks, their total area, mean area, total area per 1,000 residents, and the relative coverage of 500-meters buffer zones.

## Spatial Data

- OpenStreetMap: `leisure: [park, garden]`

::: callout-note
OpenStreetMap data may be incomplete or inconsistent, so results should be interpreted as approximate.
:::

## Workflow

- Looping through the cities' boundaries and extracting the parks info for each city.
- Park information is structured as `Dictionary` - Key: City's name, Value: Parks GeoDataFrame
- CRS transformation to Israeli TM Grid (EPSG: 2039)
- Spatial analysis
- Simple analysis with static and interactive visualization

**CRS:**

For this analysis I'll use [*Israel 1993 / Israeli TM Grid*](https://epsg.io/2039-9676) (EPSG: 2039)

# Data Preparation

```{python}
#| code-summary: Importing packages

import osmnx as ox  # OpenStreetMap API
import pandas as pd
import folium
import geopandas as gpd
import matplotlib.pyplot as plt
import contextily as cx  # Add basemaps to gdf.plot()
import plotly.express as px  # Interactive plots
```

**Cities df:**

I'll start by creating a pd.DataFrame of the cities and the population

```{python}
#| code-summary: Initial cities df

cities_df = pd.DataFrame({"osm_id": ['R1383629', 'R1383631', 'R1383630'], "name": ["Hod Hasharon", "Kfar Sava", "Raanana"], "population_k": [63, 101, 75]})

cities_df
```

::: callout-note
Estimated population data ["World Population Review"](https://worldpopulationreview.com/cities/israel)
:::

To separate the cities' info, I use dictionaries for the gdf - key = city, value = gdf

**Cities boundaries:**

```{python}
#| code-summary: Extract cities boundaries

# Create list of osm_id:
osm_id_list = cities_df['osm_id'].to_list()

# Create a gdf of the OSM features:
geoms_gdf = ox.geocode_to_gdf(osm_id_list, by_osmid=True)

# Attach the geometry column to the original cities_df:
cities_df['geometry'] = geoms_gdf['geometry'].values

# Convert cities_df to cities_gdf:
cities_gdf = gpd.GeoDataFrame(cities_df, geometry='geometry', crs='EPSG:4326')


```

**Cities parks:**

```{python}
#| code-summary: Extract parks info

# Creating dictionary of cities' parks(key = city name, value = parks gdf)
# For each gdf - clean data and calculate parks' areas

parks = {}
tags = {'leisure': ['park', 'garden']}

for row in cities_gdf.itertuples():
    
    # Extracting OSM data and convert CRS:
    parks[row.name] = ox.features_from_polygon(
        row.geometry, 
        tags=tags
        ).to_crs(epsg=2039)


    # Clearing out non Polygon/MultiPolygon features:
    parks[row.name] = parks[row.name][parks[row.name].geometry.geom_type.isin(
        ["Polygon", "MultiPolygon"])]

    # Clearing out unnecessary columns:
    parks[row.name] = parks[row.name][["geometry", "name"]]

    # Calculating area for each park:
    parks[row.name] = parks[row.name].assign(
        area_m2=lambda df: df.geometry.area
    )

# Changing the cities CRS to epsg: 2039
cities_gdf = cities_gdf.to_crs(epsg=2039)
```

**Mapping:**

```{python}
#| code-summary: Interactive mapping
#| echo: false

# Create base map
m = cities_gdf.explore(
    column="name",
    tooltip=False,
    name="Cities",
    legend=True
)

# Add parks layers
for idx, row in cities_gdf.iterrows():
    parks[row["name"]].explore(
        m=m,
        color="green",
        tooltip="name",
        name = f"{row['name']} Parks"
    )

# Additional map settings - basemap and layer control
folium.TileLayer("CartoDB positron").add_to(m)
folium.LayerControl().add_to(m)

m
```

# Analysis

## Basic Statistic

```{python}
#| code-summary: Calculate parks statistics

# Total numbers of parks per city:
cities_gdf["parks_no"] = cities_gdf["name"].apply(
    lambda x: len(parks[x]))

# Total parks' area per city:
cities_gdf["total_parks_area_dunam"] = cities_gdf["name"].apply(
    lambda x: parks[x]["area_m2"].sum())/1000

# Average parks' area per city:
cities_gdf["mean_parks_area_dunam"] = cities_gdf["name"].apply(
    lambda x: parks[x]["area_m2"].mean())/1000

# Total parks' area per 1,000 population:
cities_gdf["park_area_per_1k_pop"] = round(cities_gdf["total_parks_area_dunam"] / cities_gdf["population_k"], 2)

```

```{python}
#| code-summary: summary table
#| label: tbl-summary
#| tbl-cap: Summary Table
#| tbl-cap-location: bottom
#| echo: false

# Create a dictionary for titles
clean_labels = {
    "parks_no": "Number of Parks",
    "total_parks_area_dunam": "Total Parks Area (Dunam)",
    "mean_parks_area_dunam": "Mean Parks Area (Dunam)",
    "park_area_per_1k_pop": "Parks Area (Dunam) per 1,000 Population",
}

table = cities_gdf[["name", "parks_no", "total_parks_area_dunam", "mean_parks_area_dunam", "park_area_per_1k_pop"]]

table = table.round(2)

table = table.rename(columns=clean_labels)

table
```

```{python}
#| code-summary: Statistic charts plots
#| label: fig-bar-plots
#| fig-cap: Cities' Parks Statistics
#| echo: false

# Create 'Long' df for plotly, each row contain: city name, maetric name and the value
# The df is 12 rows (cities * metrics) X 3 columns
df_long = cities_gdf.melt(
    id_vars="name",
    value_vars=list(clean_labels.keys()),
    var_name="Metric",
    value_name="Value"
)

# Create facet of 4 plots (one for each metric)
fig = px.bar(
    df_long,
    x="name",
    y="Value",
    facet_col="Metric",
    facet_col_wrap=2,
    color="name",
    labels={"name": "City Name", "Value": "Measurement"},
    height=500,
    facet_row_spacing=0.1,
    facet_col_spacing=0.07
)

# Change the default plotly title ("Metric = ...") with a correct title
# according the dict above
fig.for_each_annotation(lambda a: a.update(text=clean_labels.get(a.text.split("=")[-1], a.text)))

fig.update_traces(width=0.5)  # Columns width in plot
fig.update_yaxes(matches=None, showticklabels=True)  # y-axis modification
fig.update_layout(showlegend=False)
fig.show()
```

::: callout-note
1 Dunam = $1,000 m^2$
:::

::: panel-tabset
```{python}
#| echo: false
#| code-summary: Map plot function

def map_plot(col, title):
    # Create base map
    ax = cities_gdf.set_geometry("geometry").plot(column=col, alpha=0.5, legend=True)
    cx.add_basemap(ax, source=cx.providers.CartoDB.PositronNoLabels, crs=cities_gdf.crs)
    plt.title(title, size=15)

    # Add city name labels
    for row in cities_gdf.itertuples():
        centroid = row.geometry.centroid
        ax.annotate(
            text = row.name,
            xy = (centroid.x, centroid.y),
            size = 8,
            horizontalalignment = 'center'
        )
        
    plt.show()

map_plot("parks_no", "Number of Parks")
```

## Number of Parks

```{python}
#| code-summary: Map Plot
#| echo: false

map_plot("parks_no", "Number of Parks")
```

## Total Parks Area

```{python}
#| code-summary: Map Plot
#| echo: false

map_plot("total_parks_area_dunam", "Total Parks Area (Dunam)")

```

## Mean Parks Area

```{python}
#| code-summary: Map Plot
#| echo: false

map_plot("mean_parks_area_dunam", "Mean Parks Area (Dunam)")

```

## Parks Area per 1,000 Population

```{python}
#| code-summary: Map Plot
#| echo: false

map_plot("park_area_per_1k_pop", "Parks Area (Dunam) per 1,000 Population")

```
:::

### Parks Coverage

While park availability provides a general comparison, it does not capture how easily residents can actually reach these parks. Accessibility is estimated by creating 500-meters buffer around parks (representing approximate walking distance) and calculating their coverage relative to the total city area.

::: callout-note
Land-use and residential distribution are not considered in this analysis.

The results should be interpreted as a relative measure of spatial proximity rather than actual walking accessibility.
:::

```{python}
#| code-summary: Calculating parks buffer coverage area

# Create buffer 500 m around the parks
cities_gdf['parks_buffer'] = cities_gdf['name'].apply(lambda city_name: parks[city_name].buffer(500).union_all())

# Define as geometry type column and set CRS
cities_gdf.set_geometry("parks_buffer", inplace=True)
cities_gdf["parks_buffer"] = cities_gdf["parks_buffer"].set_crs(epsg=2039)

# Calculating cities area
cities_gdf["city_area"] = cities_gdf.set_geometry("geometry").area/1000

# Calculating un-buffered area
cities_gdf["unbuffered_area"] = (
    cities_gdf["geometry"].difference(cities_gdf["parks_buffer"]).area / 1000
)


# Calculating un-buffered percentage
cities_gdf["unbuffered_perc"] = cities_gdf["unbuffered_area"] / cities_gdf["city_area"] * 100

```

:::: {#fig-maps-tabset}
::: panel-tabset
```{python}
#| echo: false
#| code-summary: City plot map function

def city_map(city_name):
    c_df = cities_gdf[cities_gdf['name'] == city_name]

    city_covered = str(round(100 - c_df["unbuffered_perc"].iloc[0], 1))

    ax = c_df.set_geometry("geometry").plot(alpha=0.3, edgecolor='black') # Plot city's polygon

    c_df["parks_buffer"].intersection(c_df["geometry"]).plot(ax=ax, color='green', alpha=0.3) # Plot parks buffer only inside city's boundary
    parks[city_name].plot(ax=ax, color='green') # Plot parks
    cx.add_basemap(ax, source=cx.providers.CartoDB.PositronNoLabels, crs=cities_gdf.crs)

    plt.title(f"{city_name}, {city_covered}% Area Covered", size=15)

    plt.show()

```

## Hod Hasharon

```{python}
#| code-summary: City's parks coverage plots
#| echo: false

city_map("Hod Hasharon")
```

## Kfar Sava

```{python}
#| code-summary: City's parks coverage plots
#| echo: false

city_map("Kfar Sava")
```

## Raanana

```{python}
#| code-summary: City's parks coverage plots
#| echo: false

city_map("Raanana")
```
:::

Parks' 500 meter buffer (green area) coverage area
::::

Note: Cities with large peripheral parks may appear more accessible in buffer-based analysis, even when those parks are less usable for daily access.

### Key Findings

- Hod Hasharon has fewer parks overall, both by number and total area
- Raanana has the largest number of parks, but their average area is the smallest, nevertheless, it maintains the highest park area per capita.
- Kfar Sava has the largest average parks area
- Both Kfar Sava and Raanana have similar parks' accessibility coverage characteristics which covers almost the whole cities area, while Hod Hasharon has a significant portion of its area outside the 500-meter accessibility. (Note: Most of the areas in south-west Hod Hasharon are open fields and industrial)

# Conclusion

```{python}
#| echo: false

# Measurements for the text below
cities = cities_gdf['name'].to_list()

cities_gdf_index = cities_gdf.set_index('name')

stats = {}
for city in cities:
    stats[city] = {
        "parks_no": cities_gdf_index.loc[city, "parks_no"],
        "total": round(cities_gdf_index.loc[city, "total_parks_area_dunam"], 2),
        "mean": round(cities_gdf_index.loc[city, "mean_parks_area_dunam"], 2),
        "per_capita": round(cities_gdf_index.loc[city, "park_area_per_1k_pop"], 2),
        "covered": round(100 - cities_gdf_index.loc[city, "unbuffered_perc"], 1)
    }
```

As we can see from @fig-bar-plots the three cities have different public parks characteristics.

Hod Hasharon has significantly fewer parks (`{python} str(stats["Hod Hasharon"]["parks_no"])`) compared to the other two cities. Although its parks are slightly larger on average (`{python} str(stats["Hod Hasharon"]["mean"])` dunam), this does not compensate for the lower total park area (`{python} str(stats["Hod Hasharon"]["total"])` dunam) and park area per capita (`{python} str(stats["Hod Hasharon"]["per_capita"])` Dunam per 1,000 population).

Kfar Sava has fewer parks (`{python} str(stats["Kfar Sava"]["parks_no"])`) than Raanana, but they are larger on average (`{python} str(stats["Kfar Sava"]["mean"])` dunam). In contrast, Raanana has more parks (`{python} str(stats["Raanana"]["parks_no"])`) with smaller average size (`{python} str(stats["Raanana"]["mean"])` dunam), resulting in the highest park area per capita among the three cities.\
(Raanana has `{python} str(stats["Raanana"]["per_capita"])` Dunam per 1,000 population, while Kfar Sava has `{python} str(stats["Kfar Sava"]["per_capita"])`.)

The higher parks area per capita in Raanana may reflect lower population density or different urban planning priorities.

In @fig-maps-tabset we can see the parks potential accessibility of 500 meters zone buffer around the parks and its relatively area to the cities total areas. Here as well, Hod Hasharon has significantly lower ratio (`{python} str(stats["Hod Hasharon"]["covered"])`%) compared to Kfar Sava (`{python} str(stats["Kfar Sava"]["covered"])`%) and Raanana (`{python} str(stats["Raanana"]["covered"])`%)

The lower ratio in Hod Hasharon is caused mainly in the city's residential spread which is concentrated in its eastern areas.

# Method Summary

In this analysis I used spatial information to compare basic statistics calculations between three similar cities.

- Extract parks data from OpenStreetMap for each city by looping
- Clean and filter geometries
- Reproject data for accurate measurements
- Calculate parks statistics for each city
- Create parks buffer zones and calculate areas ratio
- Visualize the results

## Advanced action-items

Here's some advanced action-items which can be made on this project:

- Network Analysis for more accurate accessibility analysis
- Accurate land-use and population distribution mapping can refine the parks spreads relatively to residents areas
