project:
  type: website
  output-dir: docs
  
date: last-modified
date-format: DD/MM/YYYY

website:
  title: "My Spatial World"
  description: "Spatial Analysis and Tutorials"

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:  
      - section: Projects
        contents:
          - auto: "projects/*.qmd"

      - section: Tutorials
        contents:
          - auto: "tutorials/*.qmd"

      - about.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    code-overflow: wrap
    code-fold: true
    lightbox: true

execute: 
  freeze: auto
  echo: true
  error: true
  warning: false
  
keep-ipynb: false


quarto:
  python: ./.venv/Scripts/python.exe
  



