---
title: "Project Setup Guide"
from: markdown+emoji
---

# Overview

My main goal with this project is to create a blog / web site about spatial analysis, with two main focuses: **analysis project** where I analyze a specific issue, and **tutorial topics** where I explain a specific issue (mostly for my future self!).

I will be using Python, R and SQL with duckdb, utilizing Positron with Quarto

Instead of trying to build the whole website at once, I'm using a "staged approach":

1.  Create some standalone `.qmd` files in organized subfolders.

2.  Once initial content is ready, implement a Quarto Website structure to glue them together.

# Preparing the Folder

## 1. Initialize the Environment

I started by creating an R project folder in Positron with renv for reproducible R dependencies and Git-ready version control. Next, I added a Python environment using `UV`: `{pwsh} uv init`

## 2. Core Packages

I installed the primary spatial and data science packages for each language:

**Python** (`uv add`):

-   `geopandas`, `rasterio` (Vector/Raster analysis)

-   `duckdb` (SQL)

-   `matplotlib` (Visualization)

-   `folium`, `leafmap` (Interactive Visualization)

-   `jupyter` (Engine support)

**R** (`install.packages`):

-   `tidyverse` (Data Science packages collection)

-   `sf` (Vector analysis)

-   `terra` (Raster analysis)

-   `reticulate` (The bridge between R and Python)

::: callout-note
I am using `reticulate` for the integration between R and Python environments in the same `*.qmd` file.
:::

## 3. The environment Bridge

The biggest challenge was ensuring `reticulate` could find the `uv` environment when rendering files inside subfolders.

For local work on Positron, I use a `.Renviron` file in the project root, which is **Git-ignored**:

```         
# .Renviron (Local only!)
RETICULATE_PYTHON = "../.venv/Scripts/python.exe"
```

::: callout-note
In this manner, the `.qmd` files need to be inside a one-level sub-folder and not directly in the project root. For more flexibility, a full path should be provided
:::

## 4. Folder Structure

The repository is organized into two main content folders:

-   `projects/`: Analysis projects

-   `tutorials/`: General guides

**And now our repository is ready!**

# Creating the Website

## 1. Implement a Quarto Website Project

::: callout-tip
[Quarto](https://quarto.org/) has good site with guides and explanations about its files and projects format
:::

After creating the first few `.qmd` files, it's time to implement the Website Project. First I created a separate 'test' folder for the Quarto Website Project. That gave me the chance to "play" and test the features with this format in a clean and safe environment.

After familiarizing myself with the Project's format, I copied the relevant files: `_quarto.yml`, `index.qmd`, `about.qmd` and `styles.css` to the repository root.

In `_quarto.yml` file added the line:

```         
project:
  output-dir: docs
```

Doing this, make deployment of the page through GitHub Pages, much easier.

## 2. Publish in GitHub

Once the site is updated, the necessary steps are:

-  `{pwsh} quarto render` 

-  `{pwsh} git add .` 

- `commit`

- `push`